### Create account
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
  "username": "testuser"
}

### Get all accounts
GET http://localhost:3000/api/v1/accounts

### Get account by id
GET http://localhost:3000/api/v1/accounts/69f916b2-d61d-4d19-8bbb-6481dbaae818

### Update account
PATCH http://localhost:3000/api/v1/accounts/69f916b2-d61d-4d19-8bbb-6481dbaae818
Content-Type: application/json

{
  "balance": 1000
}

### Delete account
DELETE http://localhost:3000/api/v1/accounts/1
