### Get all posts
GET http://localhost:3000/posts

### Get post by id
GET http://localhost:3000/posts/1

### Create post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Test Post",
  "content": "This is a test post"
}

### Update post
PATCH http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "Updated Post",
  "content": "This post has been updated"
}

### Delete post
DELETE http://localhost:3000/posts/1
